### ISSUE TITLE
FormatException

### ISSUE THREAD

**Issue by olk** [go-vikunja/app#48]
Hi,
 I get an error on version 0.22 at login from the app:
"Error on request: FormatException: Unexpected character (at character 1) <!DOCTYPE html>
                                                                                                                       ^"
Backend is version 0.21

**Comment by Benimautner** [comment]
Normally this only happens if you enter your frontend version instead of your backend version in the server address field.
The app supports two login procedures, which do the same but work fundamentally differently.

If you want to log in with the frontend, enter your frontend URL and click on "login with frontend"
if you want to log into the API only, enter the API URL in the server address field, fill in user and password and click login.

hope this helps, feel free to reopen the issue if you still need help.

**Comment by justcallmedudedude** [comment]
> Normally this only happens if you enter your frontend version instead of your backend version in the server address field. The app supports two login procedures, which do the same but work fundamentally differently.
> 
> If you want to log in with the frontend, enter your frontend URL and click on "login with frontend" if you want to log into the API only, enter the API URL in the server address field, fill in user and password and click login.
> 
> hope this helps, feel free to reopen the issue if you still need help.

I was getting the same issue, but when I login with frontend I get a different error:
`Error on request: HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: Hostname mismatch(handshake.cc:393))`

If it matters, I have my reverse proxy setup using this guide (method 1) https://vikunja.io/docs/reverse-proxy/#method-1 where I have two different DNS entries for the frontend and api.
