### ISSUE TITLE
Can't create task in home tab

### ISSUE THREAD

**Issue by cercatrova21** [go-vikunja/app#49]
Installed API: 0.22.0
Frontend Version: 0.22.0 
Installed app: 0.1.2-beta

When I click on the + symbol on the home screen and want to create a new task, the following error message appears: Please select a default list in the settings. 
However, I have set the default list. I have also run tests by changing the list. The change is saved in the database (I can see the changed default list on the server). No matter what I have selected, no tasks can be created via the home screen.

If you go to the project page, select a project and enter the task there, it works.

**Comment by Benimautner** [comment]
Oh yeah, you're right sorry about this. I didn't notice because even though it was getting the new default project from the API, it still used the old one in the device storage. Since you probably set up your app after the release came out or at least cleared the storage, it didn't work for you, but I didn't catch it during testing. I will publish a new release in a couple of hours with this fixed, please report back after you tried the new release!

**Comment by cercatrova21** [comment]
It works now, thank you :)
